In [1]:
import pandas as pd
import numpy as np
%matplotlib inline
a='a'
b=2
f'{a*3}{b}'
(lambda n:n**2) (15)
c=pd.Series(range(1,5),index=list('abcd'))
c.values
c.index
c.rename({'a':'aa'},inplace=True)
data = [['Alex',10],['Bob',12],['Clarke',13]]
c = pd.DataFrame(data,columns=['Name','Age'])
c
# c.to_feather("train.feather")
# c*2
# c.describe()
# c.nunique()
# c.value_counts().sort_index().plot(kind='bar')
# df = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
# df.rename(columns={"A": "a"})

     Name  Age
0    Alex   10
1     Bob   12
2  Clarke   13

In [2]:
import pandas as pd
import numpy as np
import os 
import time

In [3]:
# station data
st_filename=r'C:\Users\user\Desktop\iis_airbox_station.csv'
st_df=pd.read_csv(st_filename)
mask1=(st_df.create_year<=2018)
mask2=(st_df.station_name.str.contains('高雄'))
mask3=(st_df.station_address.str.contains('高雄'))
st_df_kaohsiung=st_df[mask1&mask2|mask3]
st_df_kaohsiung
# st_df.filter(like='2018',axis=0)

,station_id,station_name,station_address,lat,lon,source,create_year
2,74DA38F20A0C,高雄市市立七賢國小,高雄市七賢國小 高雄市新興區七賢一路393號,22.634,120.306,Kaohsiung18,2018
4,74DA38F20EC8,高雄市市立紅毛港國小,高雄市紅毛港國小 高雄市前鎮區明鳳7街1號,22.583,120.334,Kaohsiung18,2018
9,74DA38F21146,高雄市仁武特殊教育學校,仁武特殊教育學校,22.683,120.346,Kaohsiung18,2018
11,74DA38F20B12,高雄市市立多納國小,高雄市多納國小 高雄市茂林區多納里1-2號,22.910,120.716,Kaohsiung18,2018
13,74DA38F20F1A,高雄市市立建國國小,高雄市建國國小 高雄市前金區自立二路111號,22.635,120.298,Kaohsiung18,2018
...,...,...,...,...,...,...,...
3095,74DA38F20F6E,高雄市市立甲仙國小,高雄市甲仙國小 高雄市甲仙區西安里文化路45號,23.081,120.589,Kaohsiung18,2018
3096,74DA38F20F78,高雄市市立木柵國小,高雄市木柵國小 高雄市內門區木柵里木柵3號,22.975,120.467,Kaohsiung18,2018
3098,74DA38F20FC6,高雄市市立忠孝國小,高雄市忠孝國小 高雄市鳳山區新富路630號,22.617,120.349,Kaohsiung18,2018
3099,74DA38F20FC8,高雄市市立鼎金國小,高雄市鼎金國小 高雄市三民區鼎山街375號,22.656,120.321,Kaohsiung18,2018
3103,74DA38F20FE4,高雄市市立崇德國小,高雄市崇德國小 高雄市田寮區崇德里崇德路101號,22.877,120.379,Kaohsiung18,2018

In [7]:
# 1-5 airbox data
day_file=r'C:\Users\user\Desktop\iis_airbox_2020100{}.csv'
res=pd.read_csv(day_file.format(1))
for i in range(1,6):
    tmp_read=pd.read_csv(day_file.format(i))
    res=pd.concat([res,tmp_read],verify_integrity=True,join="inner", ignore_index = True)
del st_df_kaohsiung['station_name']
del st_df_kaohsiung['station_address']

res.rename(columns={"device_id":"station_id"},inplace = True)
res=pd.merge(res,st_df_kaohsiung,on='station_id',how='inner')

res

,station_id,SiteName,PM25,timestamp,lat,lon,source,create_year
0,74DA38F20DD0,高雄市市立樂群國小(2018),4,2020-10-01 00:00:00,22.608026,120.322983,Kaohsiung18,2018
1,74DA38F20DD0,高雄市市立樂群國小(2018),5,2020-10-01 00:06:24,22.608026,120.322983,Kaohsiung18,2018
2,74DA38F20DD0,高雄市市立樂群國小(2018),7,2020-10-01 00:12:33,22.608026,120.322983,Kaohsiung18,2018
3,74DA38F20DD0,高雄市市立樂群國小(2018),8,2020-10-01 00:18:51,22.608026,120.322983,Kaohsiung18,2018
4,74DA38F20DD0,高雄市市立樂群國小(2018),9,2020-10-01 00:25:02,22.608026,120.322983,Kaohsiung18,2018
...,...,...,...,...,...,...,...,...
208342,74DA38F20C2C,高雄市市立民權國小(2018),32,2020-10-05 23:27:12,23.248000,120.702000,Kaohsiung18,2018
208343,74DA38F20C2C,高雄市市立民權國小(2018),31,2020-10-05 23:33:25,23.248000,120.702000,Kaohsiung18,2018
208344,74DA38F20C2C,高雄市市立民權國小(2018),31,2020-10-05 23:45:46,23.248000,120.702000,Kaohsiung18,2018
208345,74DA38F20C2C,高雄市市立民權國小(2018),31,2020-10-05 23:51:57,23.248000,120.702000,Kaohsiung18,2018
208346,74DA38F20C2C,高雄市市立民權國小(2018),32,2020-10-05 23:58:07,23.248000,120.702000,Kaohsiung18,2018

In [8]:
feather_save_path=r"C:\Users\user\Desktop\df.feather"
json_save_path=r"C:\Users\user\Desktop\df.json"

start_time=time.time()
res.to_feather(feather_save_path)
end_time=time.time()
print(f'save file to feather during time: {end_time-start_time} sec')

start_time=time.time()
res.to_json(json_save_path)
end_time=time.time()
print(f'save file to json during time: {end_time-start_time} sec')


feather_size=os.path.getsize(feather_save_path)
json_size=os.path.getsize(json_save_path)
print(f'feather size: {feather_size} bytes \njson size: {json_size} bytes')

save file to feather during time: 0.33496832847595215 sec
save file to json during time: 1.7557313442230225 sec
feather size: 4966890 bytes
json size: 42676487 bytes